### ISSUE TITLE
Convert file from MemoryStream

### ISSUE THREAD

**Issue by Jercyvz** [pdftables/csharp-pdftables-api#1]
Hello! Can you help me with this question. I need to read pdf file from Memory stream and put it to request . Is it possible ?
Thanks!

**Comment by pwaller** [comment]
Have you tried passing your memory stream to the [`StreamContent constructor`](https://github.com/pdftables/csharp-pdftables-api/blob/f45f2778a3aa38010311750fc17efe5865883c26/pdftables.cs#L25)?

```c#
    var client = new HttpClient();
    var upload = new StreamContent(f); // pass a memory stream as f instead of a file stream
    var mpcontent = new MultipartFormDataContent();
    Console.WriteLine("Uploading content...");
    mpcontent.Add(upload);

    using (var response = await client.PostAsync(uploadURL, mpcontent))
```

**Comment by Jercyvz** [comment]
Hi Peter! 
Thanks for the fast answer. 
Yes, I've tried to do this but no success. OCR System gave me HTML page with "Unknown format" error.

**Comment by Jercyvz** [comment]
Hi Peter! Sorry for spending your time, I've changed the way for MemoryStream creation and now my code is working. Thanks!

**Comment by pwaller** [comment]
Great! It's good etiquette to close issues when you consider them as not needing a followup. Good luck!
